# Generated by Django 2.0 on 2018-10-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181022_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readed_time',
            field=models.IntegerField(default=0),
        ),
    ]
